version: '3'

services:

### Balanceador de carga ( HAproxy )

  loadbalancer:
    image: debian/haproxy
    container_name: balancer
    hostname: balancer
    network_mode: host
    volumes:
      - /etc/haproxy
    depends_on:
      - db
      - memcache
      - php
      - nginx
      - varnish
      - templater
      
  templater:
    image: templater
    container_name: templater
    hostname: templater
    network_mode: host
    volumes:
      - ./haproxy.ctmpl:/tmp/haproxy.ctmpl:ro
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - loadbalancer
    command: consul-template -template "/tmp/haproxy.ctmpl:/etc/haproxy/haproxy.cfg:docker restart balancer"
    depends_on:
       - db
       - memcache
       - php
       - nginx
       - varnish
    

###

### Proxy Inverso ( Varnish)

  varnish:
    image: secoresearch/varnish
    environment:
      VARNISH_BACKEND_IP: ${VARNISH_BACKEND_IP}
      VARNISH_BACKEND_PORT: ${VARNISH_BACKEND_PORT}
    ports:
      - 80:80
    depends_on:
      - db
      - memcache
      - php
      - nginx

###

### Servidor web ( Nginx )

  nginx:
    image: nginx
    volumes:
    - ./servidor_web/conf/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 8080:80
    environment:
      - NGINX_HOST: ${NGINX_HOST}
      - NGINX_PORT: ${NGINX_PORT}
    command: /bin/bash -c "envsubst &lt; /etc/nginx/conf.d/site.conf &gt; /etc/nginx/conf.d/default.conf &amp;&amp; exec nginx -g 'daemon off;'"
    depends_on:
      - db
      - memcache
      - php

###

### Servidor PHP ( joomla )

  php:
    build:
        contest: ./servidor_aplicaciones
    ports:
      - 9000:9000
    volumes:
      - ./servidor_apliaciones/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf


    enviroment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
      - memcache

###

### Servido Cache de base de datos ( MemCache )
  memcache:
     build:
         contest: ./cache_bd
     ports:
     - 11211:11211
     enviroment:
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     depends_on:
       - db
###

### Servidor de Base de datos ( MariaDB )

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

###
