version: '1'
services:
  nginx:
    image: 'nginx:1.15'
    ports:
      - '8080:8080'
  php:
    image: 'php:latest'
  
  varnish:
    image: 'secoresearch/varnish'
    environment:
      VARNISH_BACKEND_IP:
      VARNISH_BACKEND_PORT: 8080
    ports:
      - '80:80'
  db:
    image: 'mariadb'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle_db
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: moodle
    ports:
      - '3306:3306'
volumes:
  nginx_data:
    driver: local
