version: '3'
services:
  nginx:
    image: nginx
    volumes:
    - ./servidor_web/conf/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=www.grupo2docker.org
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst &lt; /etc/nginx/conf.d/site.conf &gt; /etc/nginx/conf.d/default.conf &amp;&amp; exec nginx -g 'daemon off;'"
  php:
    image: 'php:latest'
  
  varnish:
    image: secoresearch/varnish
    environment:
      VARNISH_BACKEND_IP:172.22.201.97
      VARNISH_BACKEND_PORT: 8080
    ports:
      - "80:80"
  db:
    image: 'mariadb'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle_db
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: moodle
    ports:
      - '3306:3306'
