version: '3'

services:

### Servidor web ( Nginx )

  nginx:
    image: nginx
    volumes:
    - ./servidor_web/conf/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 8080:80
    environment:
      - NGINX_HOST: ${NGINX_HOST}
      - NGINX_PORT: ${NGINX_PORT}
    command: /bin/bash -c "envsubst &lt; /etc/nginx/conf.d/site.conf &gt; /etc/nginx/conf.d/default.conf &amp;&amp; exec nginx -g 'daemon off;'"
    depends_on:
      - db
      - php

###

### Servidor PHP ( joomla )

  php:
    build:
        contest: ./servidor_aplicaciones
    ports:
      - 9000:9000
    volumes:
      - ./servidor_apliaciones/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf


    enviroment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

###

### Servido Cache de base de datos ( MemCache )

###

### Servidor de Base de datos ( MariaDB )

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

###
